### PR TITLE
External contorller for bot

### LINKED ISSUE #81: Delegated Controller class
Hey there! 

I've started writing a fairly complex bot which might end up doing lots of different things. I would like to define `@Controller` methods outside the main Bot class however those do not get registered because the framework only looks into the main class.

```
Method[] methods = this.getClass().getMethods();
        for (Method method : methods) {
            if (method.isAnnotationPresent(Controller.class)) {
                Controller controller = method.getAnnotation(Controller.class);
...
```

I was wondering if we could extend it's functionality by adding, perhaps, a `@Handler` annotation that would indicate a class able to define `@Controller` methods.

This is kid of achievable with the current framework by having more Spring Components that extend `Bot`. However this causes multiple WebSocket connections to be open which effectively means creating more bots.

Happy to chat in more details if this sounds reasonable.

Cheers!

### PR DESCRIPTION
**Pull request by tsergey-tm**
Fixes #81. Added ability to register other beans as bot controller.

Some little fixes:
* Performance: pattern compiled only once
* Controllers methods check for compatibility on startup

### CODE REVIEW

**Comment by ramswaroop** [comment]
Firstly, thanks a lot for contributing. I haven't thoroughly looked into your PR yet but after giving it a brief look I would like to ask you whether we can register different classes via annotation?

**Comment by tsergey-tm** [comment]
Sorry for my english. :)

In the beginning, I thought that it was more correct to make a registration with a controller, since there might be several bots in the application. The code is ready for this.

Now I understand that it's not right to do several bots of the same class.

There remains a problem when it is not clear to which bot to bind the handler. I think it will be enough to make the @handler annotation in which the parameter will indicate the list of bot classes to which the handler can be bound. And if the list is empty, then the handler will be bound to all the bots.

I'll try to do it tonight.

**Comment by Ravesty** [comment]
This looks to be a great addition to the bot framework.  Beyond the merge conflicts is there anything we can do to help this pull request along?

**Comment by ramswaroop** [comment]
@Ravesty thanks for reaching out. I actually have thought to achieve this in a slightly different approach, so I have to edit this PR before merging. Moreover, I also need to update the documentation to make this PR ready.

**Pull request closed without merging**
