### PR TITLE
Issue 79 ajohnsonz

### PR DESCRIPTION
**Pull request by ajohnsonz**
Slack API doesn't seem to be working with GET requests, so I have updated it to use POST requests.

### CODE REVIEW

**Comment by ramswaroop** [comment]
Thanks for the PR @ajohnsonz but it may take me some time to review it. The big day is around the corner so involved in that.

**Comment by ramswaroop** [comment]
@ajohnsonz what do you mean by "Slack API doesn't seem to be working with GET requests"? Which Slack API are you talking about here?

**Comment by ajohnsonz** [comment]
@ramswaroop it's been a few months since I did this so things might have changed, but if memory serves correctly the default code that was bundled with jbot uses GET requests to authenticate with Slack and get all the metadata - I understand that Slack have deprecated their server-side support for GET requests and now only accept POST requests, so I updated the jbot code accordingly, which is in this PR

**Comment by ramswaroop** [comment]
In your code changes I see you have changes the rtm methods from GET to POST. However, on Slack I still see the preferred way to connect is GET. See here: https://api.slack.com/methods/rtm.connect

**Comment by ajohnsonz** [comment]
Oh, that's an excellent point - I'm afraid I can't remember exactly what the problem was I was having back when I submitted the PR, so I'm not sure exactly why I changed it. Possibly something to do with needing to pass an auth token around? I'd have to revert the changes and see what breaks, I'll try and do that in the next few days if I have some time. If no-one else is having any problems, feel free to reject the change :)

**Pull request closed without merging**
